### ISSUE TITLE
Woocomerce Single Page sidebar not appearing after update.

### ISSUE THREAD

**Issue by dyvesh** [Codeinwp/hestia#27]
Hello,

I am using Neve theme by Themelsle version 2.10.1.
Below is my side bar:
![image](https://user-images.githubusercontent.com/25434125/107850858-1fb61400-6e1f-11eb-9907-f211b9d6215d.png)
However on single product page I do not have any sidebar.
![image](https://user-images.githubusercontent.com/25434125/107850906-6b68bd80-6e1f-11eb-829b-bc816873583b.png)

Below my layout configuration:
![image](https://user-images.githubusercontent.com/25434125/107850941-b08cef80-6e1f-11eb-8450-a0149688cd58.png)

The link to my website: 
https://shop.linkvalleys.com/product/deepak-first-product/

On product page I have:
Container setting: Contained.
Sidebar: customizer setting.

Other problem:
I have to refresh my widget page on dashboard of WordPress for the footer section widget to appear.
is this a bug from the theme structure?

Thank you for helping,
Dheeraaj Dyvesh Mahadea

**Comment by cristian-ungureanu** [comment]
Hi @dyvesh. I know it took some time but we somehow missed this message. We hope the issue got fixed in the meantime. If not, I advise you to open a ticket on https://wordpress.org/support/theme/neve/ or to contact the support department directly from your Themeisle account if you're a PRO user.
As the issue refers to Neve and this is Hestia's repository, I will close it.

Have a great day! ✌️
