### ISSUE TITLE
Client Bar URL in Hestia being auto replaced in Wordpress

### ISSUE THREAD

**Issue by SharonHanoca** [Codeinwp/hestia#41]
Hi there!
I have one picture to link to one vanity URL and I am using this in the Client Bar front page section. Although the Vanity URL is set up correctly, something keeps changing it from the actual URL
(https://www.krypton.exchange/roadmap) to:
<a href="http://h2%20id=roadmapRoadmap/h2>

I've been troubleshooting with Debugging scripts and different scenarios (running plugins, etc). I'm on a deadline now so I won't have examples but the only errors I found were:
<img width="1277" alt="Screen Shot 2022-04-29 at 1 15 01 PM" src="https://user-images.githubusercontent.com/104655459/166079560-64580e38-9dbb-47b0-bd16-1ee30f5ac844.png">

The plugins I have installed:
HostGator
Creative Mail by Constant Contact
Jetpack
OptinMonster
Orbit Fox Companion
WPForms Lite
Yoast SEO

I will have to hide that section for now (and delete the custom link) in order to launch and will have to create it's own page but will leave the example for you. Also the theme's highlight bar/function disappeared immediately :(

**Comment by cristian-ungureanu** [comment]
@SharonHanoca, I cannot replicate the reported bug. My advice for you would be to deactivate plugins one by one. Maybe there is a plugin conflict somewhere. I will be happy to take a look over this if you can point me in the right direction because right now I can't find anything wrong with the Clients Bar.

I will close this issue but feel free to reopen it if you have more information.
